### ISSUE TITLE
405 method not allowed when using jikanjs

### ISSUE THREAD

**Issue by aniplaylist** [zuritor/jikanjs#6]
Hi !

I wanted to try your wrapper to call the Jikan API but I can't seem to make it work with a simple call on my app (laravel + vuejs). 

Whenever I make a call I'm having 405 method not allowed. 
Here is my code : 
```
window.jikanjs = require('jikanjs'); 

jikanjs.loadAnime(1).then(function (response) {
    console.log(response);
}).catch(function (err) {
    console.log(err);
});
```

Here's the error : 

- OPTIONS https://api.jikan.moe/v3/anime/1 405 (Method Not Allowed)
- Failed to load https://api.jikan.moe/v3/anime/1: Response for preflight does not have HTTP ok status.

The issue seems to be with Axios. Nekomata recommanded me to try with fetch() method directly on the API endpoint and it works perfectly.

Have you got any idea how to fix this?

**Comment by zuritor** [comment]
I'm sorry that the wrapper isn't working correctly for you.

At the moment i don't know what may cause the Problem.
Do you have by chance a small example app (where it isn't working) which you can provide me with?

**Comment by aniplaylist** [comment]
Here you go : 

1. clone the repo : https://github.com/AngyNoT/laravel-jikanjs
2. `composer install`
3. `npm install`
4. `php artisan key:generate`
5. `php artisan serve`
6. Then go to `http://127.0.0.1:8000/` and open the console

The request is made in the file `/resources/js/app.js `

Hope that will help :)

**Comment by zuritor** [comment]
After a little bit of research i think the problem might lay with the modification done to axios / the common Request Header. 

After the client loads app.js the wrapper sends an OPTIONS request. It's a OPTION request and not a GET request anymore because the request isn't a "simple request" (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests) anymore.

X-Requested-With and X-CSRF-TOKEN will be added to the common Request Header in the file /resources/js/bootstrap.js in line 25 and 36 (line 13977 / 13988 in /public/js/app.js). Thus the request is not a "simple request" anymore and a preflight needs to be done "in order to determine whether the actual request is safe to send" (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests#Preflighted_requests). If you remove both lines, the jikanjs wrapper does what it should do.

Why a preflight OPTION Request returns 405 (Method Not Allowed) is a Question for the Jikan API  Developers because i don't know how exactly they handle API requests.

Request Config in your Application:
`{"config":{"transformRequest":{},"transformResponse":{},"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"headers":{"Accept":"application/json","X-Requested-With":"XMLHttpRequest","X-CSRF-TOKEN":"{{some Token}}"},"method":"get","url":"https://api.jikan.moe/v3/anime/1"},"request":{}}`

I hope i could help you and If you find a other conclusion please let my know.
